/* PUSHED part "ch1-nse", version 2, 2026-10-07T08:14:21 by coordinator, at Fer's request.
   Frozen copy of outline/parts/ch1-nse.js. Do not edit this file:
   edit the draft and push again (python3 outline/publish.py ch1-nse). */
/* Part: ch1-nse. Ownership: see outline/README.md.
   Moved from sections/03-methods.js on 2026-10-07, then rebuilt as an animated scene.
   Wrapped in a block so this part's consts can't collide with other parts. */
{
section('Ch. 1 · Methods');

// Flat scene on the anchor brain (outline/contracts/anchor-brain.md): one voxel's natural vs
// matched responses (schematic) → squared error → vs unrelated pairs → 0 / ≈1 scale →
// scatter → a shift keeps r = 1 but raises the NSE → the real example-voxel numbers.
// Fer chose (2026-10-07): compact (8 beats), bars first, keep the real-values card,
// plot on top / equation below.
sc('nseExplainer', 'scenes/nse-explainer.final-ch1-nse.html?v=2', {
  todo: 'NSE explainer for a general audience (8 beats). Response values are schematic, except the last card (real example voxels).',
  notes: 'One voxel’s responses to natural sounds and to their model-matched versions. Square each difference and average; divide by the same quantity for unrelated pairs. 0 means identical responses, about 1 means no correspondence. Unlike a correlation, the NSE is sensitive to differences in mean and scale. Real example: the Region 3 voxel has the higher correlation (0.54 vs 0.43) but the higher NSE (0.70 vs 0.34). Norman-Haignere & McDermott (2018).',
});
}
