/* PUSHED part "ch1-regions", version 2, 2026-10-07T08:24:37 by coordinator, at Fer's request.
   Frozen copy of outline/parts/ch1-regions.js. Do not edit this file:
   edit the draft and push again (python3 outline/publish.py ch1-regions). */
/* Part: ch1-regions. Ownership: see outline/README.md.
   Moved verbatim from sections/03-methods.js on 2026-10-07, then rebuilt as the region
   derivation (Supplementary Figure S4) on the anchor brain. Since 2026-10-07 it also carries
   the reliable-voxel step of the retired ch1-voxel-select, and sits after ch1-nse.
   Wrapped in a block so this part's consts can't collide with other parts. */
{
section('Ch. 1 · Methods');

// scenes/region-definition.html: S4 (transposed, as in the v14_6 full text) redrawn on the
// right, after the 2018 group map and its distance gradient (NH&M 2018 Fig. 3C, 3D): nine Glasser parcels, their NSE in the Norman-Haignere & McDermott 2018 data, ranked,
// cut into three groups of three, then the region sizes and the reliable voxels per listener.
// Panel B is the anchor brain on the left, where the region being named is outlined. A reliability
// map on the brain is requested (contracts/anchor-brain-requests/ch1-regions.md).
sc('regionDefinition', 'scenes/region-definition.final-ch1-regions.html?v=2', {
  notes: 'How were these regions defined? [click] Earlier data, Norman-Haignere & McDermott (2018), 12 listeners: inside primary auditory cortex the spectrotemporal model-matched sounds drive cortex like the natural ones, NSE near 0; further out they diverge. [click] Binned by distance from primary auditory cortex, the NSE rises steadily. [click] We take the nine parcels of a standard parcellation (Glasser et al., 2016) that cover auditory cortex and rank them by their NSE on that 2018 group map: A1 and the belt lowest, the superior temporal sulcus highest. Independent data, so the regions can’t be biased toward any result here. [click] Cut into three groups of three, in rank order. [click] Region 1: A1, LBelt, PBelt, primary auditory cortex. [click] Region 2: MBelt, A4, TA2. [click] Region 3: A5, STSda, STSdp, the most non-primary cortex we measured. [click] Their sizes: 2,993, 3,693 and 5,251 vertices; 2,856, 3,312 and 3,364 in the group maps. [click] In each listener we keep only voxels that measured reliably, test-retest NSE below 0.4: a median of 787, 798 and 1,043 per listener, and all 10 listeners contribute to every region.',
  todo: 'Regions (Supp. Fig. S4) + keep reliable voxels, on the anchor brain. Pending: a reliability map in the anchor view.',
});
}
