/* PUSHED part "ch1-models", version 2, 2026-10-07T04:27:55 by Ch.1 methods (three models).
   Frozen copy of outline/parts/ch1-models.js. Do not edit this file:
   edit the draft and push again (python3 outline/publish.py ch1-models). */
/* Part: ch1-models. Ownership: see outline/README.md.
   Moved verbatim from sections/03-methods.js on 2026-10-07.
   Wrapped in a block so this part's consts can't collide with other parts. */
{
section('Ch. 1 · Methods');

/* The three models, rebuilt as a scene (scenes/three-models.html) so the figure
   can be spaced for a screen and animated: rows come out arrow by arrow, a
   bracket marks the two networks as the same network, the cochleagram runs
   through all three, a perturbation crafted for the robust network is added to
   the cochleagram again and again, one block opens up, and the matched stages
   take their colours. The previous static version (covers on image2) used
   assets/outline/models-{main,block,noise}.png. */
// ?r= busts the browser's cache of the scene: bump it whenever scenes/three-models.html changes
sc('threeModels', 'scenes/three-models.final-ch1-models.html?v=2?r=2', {
  todo: 'Models spaced out; each arrow and name comes out slowly; callout under the cochleagram; bracket beside the two networks; cochleagram runs through the models as activations; adversarial perturbation added to the cochleagram and run through the robust network, again and again.',
  notes: 'Sound → cochleagram. All start from a cochleagram. The spectrotemporal model: a bank of filters, each responding by how well it matches the sound, then their power. Two deep networks, CochResNet50, trained on words, environmental sounds and speakers — one standard-trained, one robust. [block] Under the hood: bottleneck blocks — 1×1, 3×3, 1×1 convolutions with batch norm and ReLU, plus an identity shortcut. [out] The two share architecture, tasks and training data. [robust] During training the robust network also saw adversarial perturbations, constructed against this model, again and again. [matched] The coloured stages are the ones we matched.',
});
}
