/* PUSHED part "ch1-regions", version 3, 2026-10-08T09:04:35 by coordinator, at Fer's request.
   Frozen copy of outline/parts/ch1-regions.js. Do not edit this file:
   edit the draft and push again (python3 outline/publish.py ch1-regions). */
/* Part: ch1-regions. Ownership: see outline/README.md.
   Moved verbatim from sections/03-methods.js on 2026-10-07, then rebuilt as the region
   derivation (Supplementary Figure S4) on the anchor brain. Since 2026-10-07 it also carries
   the reliable-voxel step of the retired ch1-voxel-select, and sits after ch1-nse.
   2026-10-08 (deck-wide round 4, PI feedback): split into two slides, one scene each (a
   ?from=&to= split doesn't survive publish.py), captions removed, the spoken text moved into
   the notes below as a presenter transcript, one passage per click.
   Wrapped in a block so this part's consts can't collide with other parts. */
{
section('Ch. 1 · Methods');

// Slide 1 · scenes/region-prior.html: Norman-Haignere & McDermott (2018) Fig. 3C (group NSE
// map) and Fig. 3D (NSE vs distance to primary auditory cortex), beside the anchor brain.
sc('regionPrior', 'scenes/region-prior.final-ch1-regions.html?v=3', {
  notes: 'Our regions of interest are based on the result I showed earlier. Norman-Haignere and McDermott (2018) measured responses to natural sounds and to sounds matched to them in a spectrotemporal model, in 12 participants. This is their group map of the normalized squared error between the two sets of responses. Within primary auditory cortex, outlined in white, the NSE is close to zero, so the model-matched sounds drive these voxels about as strongly as the natural sounds do. Outside primary auditory cortex, the NSE is substantially higher.\n\n[click] When voxels are binned by their distance from the centre of primary auditory cortex, the NSE increases with distance, in both hemispheres. The spectrotemporal model therefore accounts well for responses in primary auditory cortex and less well for responses in non-primary regions.',
  todo: 'The 2018 result the regions rest on: group NSE map, then NSE vs distance to primary auditory cortex.',
});

// Slide 2 · scenes/region-definition.html: S4 (transposed, as in the v14_6 full text) redrawn
// on the right: nine Glasser parcels ranked by their NSE in the 2018 group map, cut into three
// groups of three, then the region sizes and the reliable voxels per participant. The anchor
// brain on the left outlines the region being named. A reliability map on the brain is
// requested (contracts/anchor-brain-requests/ch1-regions.md).
sc('regionDefinition', 'scenes/region-definition.final-ch1-regions.html?v=3', {
  notes: 'We used this independent dataset to define our regions of interest.\n\n[click] We took the nine parcels of the Glasser et al. (2016) parcellation that cover auditory cortex and ranked them by their NSE in the 2018 group map. Vertices entered if their test-retest NSE in that dataset was below 0.15, and parcels entered if at least 100 vertices passed. A1 and the lateral belt have the lowest NSE, and the two parcels in the dorsal bank of the superior temporal sulcus the highest. Because the ranking uses only the 2018 data, the regions are independent of the measurements reported here.\n\n[click] We divided the ranking into three regions of three parcels each, in rank order. The division follows the rank order rather than the largest gaps between parcels, which fall within Regions 2 and 3.\n\n[click] Region 1 comprises A1, LBelt and PBelt, and corresponds to primary auditory cortex.\n\n[click] Region 2 comprises MBelt, A4 and TA2.\n\n[click] Region 3 comprises A5, STSda and STSdp, the most non-primary cortex we measured.\n\n[click] Across both hemispheres, the three regions contain 2,993, 3,693 and 5,251 surface vertices. Of these, 2,856, 3,312 and 3,364 are shown in the group maps, where the test-retest NSE of the group-averaged responses is below 0.4.\n\n[click] Within each region, each participant’s analysis includes only the voxels whose responses to the natural sounds were reliable, defined as a test-retest NSE below 0.4, the range in which the noise correction is well behaved. This leaves a median of 787, 798 and 1,043 vertices per participant, or 26, 22 and 20 percent of each region, and all 10 participants contribute to every region; the smallest counts are 244, 166 and 15.',
  todo: 'Regions (Supp. Fig. S4) + reliable voxels, on the anchor brain. Pending: a reliability map in the anchor view.',
});
}
