/* PUSHED part "ch1-sounds", version 1, 2026-10-07T07:04:47 by natural sounds playback.
   Frozen copy of outline/parts/ch1-sounds.js. Do not edit this file:
   edit the draft and push again (python3 outline/publish.py ch1-sounds). */
/* Part: ch1-sounds. Ownership: see outline/README.md.
   Moved from sections/03-methods.js on 2026-10-07, then animated.
   Wrapped in a block so this part's consts can't collide with other parts. */
{
section('Ch. 1 · Methods');

/* Natural sounds: one example and its matched versions, model by model; then
   the other two examples; then all 33 as dots; then the category list.
   Fer (2026-10-07): no audio on this slide; the playhead sweeps once, on "3 s".
   The panel titles ("B …", "C …") and image4's "* shown in C" are cropped off.
   The source wavs are in ~/Developer/figures/final/fig2/fig2_panelC_cochleagrams.csv.

   ACT 0 — SPANISH   (entry): Spanish vocal, natural cochleagram only.
                     (1):     "3 s" on top; the playhead sweeps it once.
   ACT 1 — MATCHED   (2-4):   its spectrotemporal → standard L2–L4 → robust L2–L4
                              versions, header and cells together, one model per click.
   ACT 2 — MORE      (5-6):   piano row, then siren row (with the axes).
   ACT 3 — ALL 33    (7):     33 dots, shaped and coloured by group as in image4.
                     (8):     the category list slides in on the left.
                     (9):     rings on the three examples in the list.

   Coordinates are in image pixels (image5 2000×590, image4 700×960), detected
   with PIL from the frame lines, tick labels and asterisks. Each image is shown
   through a crop window; chsPct() maps image pixels into the crop. */

const CHS_I5 = {W:2000, crop:[90, 62, 1925, 590]};
const CHS_I4 = {W:700,  crop:[0, 70, 700, 915]};   // list ends at y 904; "* shown in C" starts at 932
/* covers over image5, revealed on their step (neighbours overlap a few px in
   whitespace so no sub-pixel seam shows) */
const CHS_COVERS = [
  {step:2, r:[577, 62, 823, 282]},     // spectrotemporal: header + Spanish cell
  {step:3, r:[819, 62, 1372, 282]},    // standard L2–L4
  {step:4, r:[1364, 62, 1925, 282]},   // robust L2–L4
  {step:4, r:[1590, 530, 1925, 590]},  // Low–High colour bar
  {step:5, r:[90, 280, 302, 394]},     // piano: row label
  {step:5, r:[300, 225, 354, 425]},    // "Freq (kHz)" (the Spanish label ends at x 299)
  {step:5, r:[350, 280, 1925, 394]},   // piano: ticks + cells
  {step:6, r:[90, 392, 302, 590]},     // siren: row label
  {step:6, r:[350, 392, 1925, 520]},   // siren: ticks + cells
  {step:6, r:[350, 518, 620, 590]},    // time axis
];
/* camera zoom on image5 by step, anchored at the crop's top-left: close on the
   Spanish row while only natural + spectrotemporal show, pulling back as the
   networks come in (2.2× shows crop x ≤ 45%, past the spectrotemporal column;
   1.4× shows ≤ 71%, past standard L4) */
const CHS_ZOOM = [[0, 2.2], [3, 1.4], [4, 1]];
const CHS_SPANISH_NAT = [413, 184, 571, 279];   // inner plot area of the Spanish natural cell
const CHS_3S = [413, 98, 569, 113];             // "3 s" bracket (spans the cell), above the "Natural" header
/* the three starred sounds in image4 (piano, Spanish vocal, siren) */
const CHS_STARS = [[345,172,503,214], [345,494,557,538], [344,691,505,735]];
/* the 33 sounds by group, with image4's own group colours and markers */
const CHS_GROUPS = [
  {n:8,  shape:'circ', col:'#3177ac'},   // Speech
  {n:8,  shape:'tri',  col:'#a29236'},   // Human & animal
  {n:12, shape:'sq',   col:'#632045'},   // Music
  {n:5,  shape:'dia',  col:'#5b5b5b'},   // Environmental & mechanical
];

const chsAr  = ({crop:[x0,y0,x1,y1]}) => (x1-x0)/(y1-y0);
const chsImg = ({W, crop:[x0,y0,x1,y1]}) =>
  `width:${W/(x1-x0)*100}%;left:${-x0/(x1-x0)*100}%;top:${-y0/(y1-y0)*100}%`;
const chsPct = ([a,b,c,d], {crop:[x0,y0,x1,y1]}) => {
  const w = x1-x0, h = y1-y0;
  return `left:${(a-x0)/w*100}%;top:${(b-y0)/h*100}%;width:${(c-a)/w*100}%;height:${(d-b)/h*100}%`;
};

const chsCovers = CHS_COVERS.map(c =>
  `<div class="chs-cov b" data-step="${c.step}" style="${chsPct(c.r, CHS_I5)}"></div>`).join('');
const chsRings = CHS_STARS.map(r =>
  `<div class="chs-ring b" data-step="9" style="${chsPct(r, CHS_I4)}"></div>`).join('');
let chsK = 0;
const chsDots = CHS_GROUPS.map(g => `<span class="chs-grp">${
  Array.from({length:g.n}, () => `<i class="chs-dot ${g.shape}" style="--c:${g.col};--k:${chsK++}"></i>`).join('')
}</span>`).join('');

st(`
  <style>
    /* letterboxed, cropped figures that keep fitting while the layout animates
       (container units, so no engine fitFigures call is needed) */
    .chs-well{flex:1; min-height:0; min-width:0; container-type:size; display:flex; align-items:center; justify-content:center;}
    .chs-fw{position:relative; flex:none; overflow:hidden; aspect-ratio:var(--ar);
      width:min(100cqw, calc(100cqh * var(--ar))); container-type:inline-size;}
    .chs-fw > img, .chs-cam > img{position:absolute; height:auto; display:block; max-width:none;}
    .chs-cam{position:absolute; inset:0; transform-origin:0 0; transform:scale(var(--z,1));
      transition:transform 1s cubic-bezier(.4,.1,.2,1);}
    ${CHS_ZOOM.map(([k,z]) => k === 0 ? `.chs-cam{--z:${z}}` : `.slide:has(.chs-z${k}.shown) .chs-cam{--z:${z}}`).join('\n    ')}

    .chs-wrap{flex:1; min-height:0; display:flex; align-items:stretch;}
    .chs-cat{flex:0 0 0%; margin-right:0; opacity:0; display:flex; flex-direction:column; gap:1rem; min-width:0; overflow:hidden; white-space:nowrap;
      transition:flex-basis .9s cubic-bezier(.3,.7,.2,1), margin-right .9s cubic-bezier(.3,.7,.2,1), opacity .6s ease .25s;}
    .chs-right{flex:1; min-width:0; display:flex; flex-direction:column; gap:1.2rem;}
    .slide:has(.chs-mk8.shown) .chs-cat{flex-basis:30%; margin-right:3.5vw; opacity:1;}

    .chs-cov{position:absolute; background:var(--bg); transition:opacity .55s ease;}
    .chs-cov.b{opacity:1; transform:none;}
    .chs-cov.b.shown{opacity:0;}

    /* "3 s" bracket over the natural cochleagram */
    .chs-3s{position:absolute; color:var(--ochre); font-weight:700; font-size:1.4cqw; line-height:1;
      border:2px solid var(--ochre); border-top:0; border-radius:0 0 3px 3px;}
    .chs-3s.b{transform:none;}
    .chs-3s span{position:absolute; left:50%; bottom:calc(100% + .25em); transform:translateX(-50%); white-space:nowrap;}

    /* silent playhead: sweeps the Spanish natural cell once, 3 s, when "3 s" appears */
    .chs-cell{position:absolute; overflow:hidden; pointer-events:none;}
    .chs-ph{position:absolute; left:0; top:0; bottom:0; width:0; opacity:0;
      border-right:2px solid var(--ochre); background:rgba(180,83,9,.10);}
    .slide:has(.chs-mk1.shown) .chs-ph{animation:chs-sweep 3.6s linear .3s 1 both;}
    @keyframes chs-sweep{0%{width:0;opacity:1} 83%{width:100%;opacity:1} 100%{width:100%;opacity:0}}

    .chs-ring{position:absolute; border:3px solid var(--ochre); border-radius:10px; pointer-events:none;}
    .chs-ring.b{transform:scale(1.06);}
    .chs-ring.b.shown{transform:none; animation:ringpulse 1.6s ease-in-out infinite;}

    /* 33 dots, popping in one after another */
    .chs-dots{display:flex; gap:.6em; margin-top:.45em; flex-wrap:wrap;}
    .chs-grp{display:inline-flex; gap:.2em; align-items:center;}
    .chs-dot{display:inline-block; width:.55em; height:.55em; background:var(--c);
      opacity:0; transform:scale(.2); transition:opacity .25s ease, transform .3s cubic-bezier(.3,1.6,.5,1);
      transition-delay:calc(var(--k) * 45ms);}
    .chs-dot.circ{border-radius:50%;}
    .chs-dot.tri{clip-path:polygon(50% 4%, 100% 96%, 0 96%); width:.64em; height:.6em;}
    .chs-dot.dia{width:.46em; height:.46em; --r:45deg;}
    .shown .chs-dot{opacity:1; transform:rotate(var(--r,0deg));}

    .chs-mk{position:absolute; width:0; height:0;}
    .chs-bul{font-size:.95em; flex:none;}
    .chs-catcap{font-size:.8em;}
  </style>
  <h1 class="t"><em>Natural sounds</em></h1>
  <div class="chs-wrap">
    <div class="chs-cat">
      <div class="chs-well">
        <div class="chs-fw" style="--ar:${chsAr(CHS_I4)}">
          <img src="assets/final/ch1-sounds/outline/image4.png?v=1" style="${chsImg(CHS_I4)}" alt="The 33 natural sounds by category">
          ${chsRings}
        </div>
      </div>
      <ul class="frag chs-bul chs-catcap"><li>Nine categories</li></ul>
    </div>
    <div class="chs-right">
      <div class="chs-well">
        <div class="chs-fw" style="--ar:${chsAr(CHS_I5)}">
          <div class="chs-cam">
            <img src="assets/final/ch1-sounds/outline/image5.png?v=1" style="${chsImg(CHS_I5)}" alt="Cochleagrams of example natural and model-matched sounds">
            <div class="chs-cell" style="${chsPct(CHS_SPANISH_NAT, CHS_I5)}"><i class="chs-ph"></i></div>
            ${chsCovers}
            <div class="chs-3s b" data-step="1" style="${chsPct(CHS_3S, CHS_I5)}"><span>3 s</span></div>
          </div>
        </div>
      </div>
      <ul class="frag chs-bul">
        <li class="b" data-step="1">Three 3 s excerpts per sound</li>
        <li class="b" data-step="4">One matched version per excerpt, for each of <span class="hl">seven model conditions</span></li>
        <li class="b" data-step="7"><span class="hl">33 sounds</span><span class="chs-dots">${chsDots}</span></li>
      </ul>
    </div>
  </div>
  <i class="b chs-mk chs-mk1" data-step="1"></i>
  <i class="b chs-mk chs-mk8" data-step="8"></i>
  ${CHS_ZOOM.filter(([k]) => k > 0).map(([k]) => `<i class="b chs-mk chs-z${k}" data-step="${k}"></i>`).join('')}
`, {
  todo: 'Play example sounds (natural vs matched) from the cochleagrams. (Fer 2026-10-07: no audio; one playhead sweep on "3 s"; Spanish first, its matched versions model by model, then piano, siren, dots for all 33, then the category list.)',
  notes: 'A cochleagram of one natural sound, a Spanish song: frequency runs up, time runs across. [click] Each excerpt is 3 s, and there are three excerpts per sound. [click] Its matched version from the spectrotemporal model. [click] From the standard-trained network, matched at layers 2, 3 and 4. [click] And from the robust network at the same three layers: seven model conditions, one matched version per excerpt for each. [click] The same for a piano… [click] …and a siren. [click] In total, 33 natural sounds. [click] They come from nine categories in four groups: speech, human and animal sounds, music, and environmental and mechanical sounds. [click] Piano, Spanish vocal and siren are three of them.',
});
}
