/* PUSHED part "ch1-summary", version 1, 2026-10-08T09:04:35 by coordinator, at Fer's request.
   Frozen copy of outline/parts/ch1-summary.js. Do not edit this file:
   edit the draft and push again (python3 outline/publish.py ch1-summary). */
/* Part: ch1-summary. Ownership: see outline/README.md.
   Moved verbatim from sections/04-results.js on 2026-10-07.
   Wrapped in a block so this part's consts can't collide with other parts. */
{
section('Ch. 1 · Results');

st(`
  <h1 class="t">Chapter 1 <em>summary</em></h1>
  <ul class="frag" style="flex:1; justify-content:center;">
    <li class="b pine">Robust: matched sounds evoked <span class="hl">natural-like responses</span> across auditory cortex</li>
    <li class="b ochre">Standard-trained: responses <span class="hl">diverged</span></li>
    <li class="b">Predictions of natural sounds <span class="hl">missed this difference</span></li>
  </ul>
`, {
  todo: 'Bring the maps and lines back, one by one.',
  notes: 'Robust network: model-matched sounds evoked responses similar to those to natural sounds across auditory cortex. Standard-trained network: responses diverged. Predictions of natural sounds missed this difference.',
});
}
